version: '3'
volumes:
  node_modules:
services:
  web:
    image: webpack
    build: ./ReactFrontEnd
    container_name: web
    restart: always
    volumes:
      - ./ReactFrontEnd:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  api:
    build: ./CoreStart
    container_name: api_core
    restart: always
    depends_on:
      - db
  # node:
  #   build: ./NodeStart
  #   command: npm run start
  #   container_name: api_node
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  # python:
  #   build: ./PythonStart
  #   container_name: api_python
  #   volumes:
  #     - ./PythonStart:/mnt
  #   ports:
  #     - "4000:4000"
  nginx: 
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "9000:9000"
    expose:
      - 9000
    links:
      - web
      - api
      # - node
      # - python
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx/
  # mongodb:
  #   image: mongo:3.6.1
  #   container_name: uv-mongodb
  #   volumes:
  #     - mongodb:/data/db
  #     - mongodb_config:/data/configdb
  #   volumes:
  #     - ./db/data/mongo:/data/db
  db:
    container_name: db
    image: "microsoft/mssql-server-linux"
    restart: always
    ports:
      - "1433:1433"
    expose: 
      - 1433
    volumes:
      - ./db/data/mssql:/var/opt/mssql/data
      - ./db/logs/mssql:/var/opt/mssql/log
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "D.`(>q8'5d,ngL>H"