version: '3'
volumes:
  node_modules_react:
  node_modules_vue:
  esdata1:
services:
  # vue:
  #   build: ./VueFrontEnd
  #   container_name: vueweb
  #   restart: always
  #   volumes:
  #     - ./VueFrontEnd:/usr/src/vue
  #   ports:
  #     - "8082:8080"
  web:
    build: ./ReactFrontEnd
    container_name: web
    restart: always
    volumes:
      - ./ReactFrontEnd:/usr/src/app
    ports:
      - "8080:8080"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9299:9200"
      - "9399:9300"
    expose:
      - 9299
      - 9399
  api:
    build: ./CoreStart
    container_name: api_core
    restart: always
    environment:
      - ConnectionStrings:DefaultConnection=Data Source=db;Initial Catalog=CoreStart;Persist Security Info=True;User ID=sa;Password=D.`(>q8'5d,ngL>H
      - ElasticSearch:DefaultNode=http://localhost:9299
      - ForwardedHeaders=web
    depends_on:
      - db
      - elasticsearch
  nginx: 
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "9000:9000"
    expose:
      - 9000
    links:
      - web
      # - vue
      - api
      # - node
      # - python
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx/
  db:
    container_name: db
    image: "microsoft/mssql-server-linux"
    restart: always
    ports:
      - "1433:1433"
    expose: 
      - 1433
    volumes:
      - ./db/data/mssql:/var/opt/mssql/data
      - ./db/logs/mssql:/var/opt/mssql/log
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "D.`(>q8'5d,ngL>H"